server:
  port: 9001

logging:
  level:
    com:meraj: DEBUG

spring:
  application:
    name: images-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost